# Generated by Django 4.0.4 on 2022-05-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='created_at',
            new_name='date_created',
        ),
    ]
