# Generated by Django 4.0.4 on 2022-05-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_rename_created_at_album_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
